development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rf
  pool: 5
  username: root
  password: root
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rf
  pool: 5
  username: root
  password: 
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rf
  pool: 5
  username: root
  password: 
  socket: /var/lib/mysql/mysql.sock
